2025-07-14 00:17:22,358:DEBUG:certbot._internal.main:certbot version: 4.1.1
2025-07-14 00:17:22,358:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-07-14 00:17:22,358:DEBUG:certbot._internal.main:Arguments: ['--standalone', '-d', 'api.rcdigitais.com.br', '--agree-tos', '-m', 'rciolette@gmail.com', '--no-eff-email']
2025-07-14 00:17:22,358:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-07-14 00:17:22,411:DEBUG:certbot._internal.log:Root logging level set at 30
2025-07-14 00:17:22,412:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2025-07-14 00:17:22,412:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0xffff9526fc80>
Prep: True
2025-07-14 00:17:22,413:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0xffff9526fc80> and installer None
2025-07-14 00:17:22,413:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2025-07-14 00:17:22,454:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2527025161', new_authzr_uri=None, terms_of_service=None), 36a35448c679cf4dbd48de58c019bed9, Meta(creation_dt=datetime.datetime(2025, 7, 13, 23, 59, 53, tzinfo=datetime.timezone.utc), creation_host='22ca5a093fc4', register_to_eff=None))>
2025-07-14 00:17:22,454:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-07-14 00:17:22,455:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-07-14 00:17:23,006:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 995
2025-07-14 00:17:23,007:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 14 Jul 2025 00:17:22 GMT
Content-Type: application/json
Content-Length: 995
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "BvBL2UPjcbI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "https://letsencrypt.org/docs/profiles#classic",
      "shortlived": "https://letsencrypt.org/docs/profiles#shortlived (not yet generally available)",
      "tlsserver": "https://letsencrypt.org/docs/profiles#tlsserver"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.5-February-24-2025.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/acme/renewal-info",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-07-14 00:17:23,011:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for api.rcdigitais.com.br
2025-07-14 00:17:23,020:DEBUG:acme.client:Requesting fresh nonce
2025-07-14 00:17:23,021:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-07-14 00:17:23,194:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-07-14 00:17:23,196:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 14 Jul 2025 00:17:23 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 6etVd_hwO_MgkgaSikx0VNCbrrhXL5XUgnYuIi5CcxEBiwEyBA4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-07-14 00:17:23,196:DEBUG:acme.client:Storing nonce: 6etVd_hwO_MgkgaSikx0VNCbrrhXL5XUgnYuIi5CcxEBiwEyBA4
2025-07-14 00:17:23,197:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "api.rcdigitais.com.br"\n    }\n  ]\n}'
2025-07-14 00:17:23,206:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjUyNzAyNTE2MSIsICJub25jZSI6ICI2ZXRWZF9od09fTWdrZ2FTaWt4MFZOQ2JycmhYTDVYVWduWXVJaTVDY3hFQml3RXlCQTQiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "tOjSi5KPs-WWyzQ5KyCwmg1Mft4OfQGMUtoYYn8TlIQChTjPTZdaAu1CFfuqmmiXLP-RViWk5BQiBC5v_Dz_-Upj6klCzORu-Q_uu5GyzZwGa5xIfw6Hq7HqnV8yU3h4qf6FdM-9PBEDnDEq2g1ZvrD1v5WdyJXfqvACQzDsA_sNv-sXvUj4Lh6VNmvAhraW24_yE1vH0VKSjzKxjdy5eQoj7jrAeicg3ueH2h0V3sMGxnTyKnO6zw8o66_-Fy1APUqky_hwHbpL3VBRuZNWXAP8MIrUJS6eWafJH4l2WXLTQmsspeMJCq_ev8gBuGLhXLqvxbrzCS-1YSQb4PPSuQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImFwaS5yY2RpZ2l0YWlzLmNvbS5iciIKICAgIH0KICBdCn0"
}
2025-07-14 00:17:23,430:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 355
2025-07-14 00:17:23,431:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 14 Jul 2025 00:17:23 GMT
Content-Type: application/json
Content-Length: 355
Connection: keep-alive
Boulder-Requester: 2527025161
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2527025161/406311757151
Replay-Nonce: iGGS-kORf9ewDj_Ly5ieLgLjaDBiEzTXbdzLJwISqhy8zygla7M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-07-21T00:17:23Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "api.rcdigitais.com.br"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2527025161/552413074841"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2527025161/406311757151"
}
2025-07-14 00:17:23,432:DEBUG:acme.client:Storing nonce: iGGS-kORf9ewDj_Ly5ieLgLjaDBiEzTXbdzLJwISqhy8zygla7M
2025-07-14 00:17:23,433:DEBUG:acme.client:JWS payload:
b''
2025-07-14 00:17:23,438:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2527025161/552413074841:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjUyNzAyNTE2MSIsICJub25jZSI6ICJpR0dTLWtPUmY5ZXdEal9MeTVpZUxnTGphREJpRXpUWGJkekxKd0lTcWh5OHp5Z2xhN00iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzI1MjcwMjUxNjEvNTUyNDEzMDc0ODQxIn0",
  "signature": "CMrqi_PycCB_n4hcrlhtlZaiGl4zmwYCInoUjWjQ7EtuX_bM1uzuMtXk8qzIavKTrs3RKNgKTIoV_JeIMGtMo_swiC2nSuHn0N9Kgm1LnwoGOLbQt1QmIXnNCIyXPkHM90e_69O-Nfc-T7h2IRYfINmYrWFScuAvXBKA9XsHQg6IlO15QZ_CGn6a4evMDBmk8tERhxXRv118U4nVof75UdaYptMb0Ox60irm9srI9XHSY-kxFrLeZ8-yHCy4WENin8_e3B8cCiyETqFo_rgguj4EQ4FG62usWA8FzAHpFE74dGmoipwIJl6g_6NISP9AlBdB3oKtVha4reiBaFAprg",
  "payload": ""
}
2025-07-14 00:17:23,618:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2527025161/552413074841 HTTP/1.1" 200 829
2025-07-14 00:17:23,619:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 14 Jul 2025 00:17:23 GMT
Content-Type: application/json
Content-Length: 829
Connection: keep-alive
Boulder-Requester: 2527025161
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 6etVd_hwL-g0e-y9eSPNJ1h6rrxJbvPc9YsxJIwZgwLZsyrO2L0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "api.rcdigitais.com.br"
  },
  "status": "pending",
  "expires": "2025-07-21T00:17:23Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/lrf9oQ",
      "status": "pending",
      "token": "4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/VONGcg",
      "status": "pending",
      "token": "4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/ihGChQ",
      "status": "pending",
      "token": "4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI"
    }
  ]
}
2025-07-14 00:17:23,620:DEBUG:acme.client:Storing nonce: 6etVd_hwL-g0e-y9eSPNJ1h6rrxJbvPc9YsxJIwZgwLZsyrO2L0
2025-07-14 00:17:23,622:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-07-14 00:17:23,622:INFO:certbot._internal.auth_handler:http-01 challenge for api.rcdigitais.com.br
2025-07-14 00:17:23,623:DEBUG:acme.standalone:Successfully bound to :80 using IPv6
2025-07-14 00:17:23,624:DEBUG:acme.standalone:Certbot wasn't able to bind to :80 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
2025-07-14 00:17:23,630:DEBUG:acme.client:JWS payload:
b'{}'
2025-07-14 00:17:23,641:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/lrf9oQ:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjUyNzAyNTE2MSIsICJub25jZSI6ICI2ZXRWZF9od0wtZzBlLXk5ZVNQTkoxaDZycnhKYnZQYzlZc3hKSXdaZ3dMWnN5ck8yTDAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzI1MjcwMjUxNjEvNTUyNDEzMDc0ODQxL2xyZjlvUSJ9",
  "signature": "wlF7iyOVwaLaKSqKDw2wl4LswN27NGQG5a6azoEAu6fRMHIMP0vqvpb6TQYSVn9LlZbZCAUHOCqwGnB7UqO6DnbGH73yHMuVDj3gc9PEgErPBuZd1hYXYKXEV5WDQsDhurx8b8fugLyQwQT1ZtlWgZvcXZi4mZ3_MfQsxmpthH1-ha6O9U_-MkwoCij7jusC_uXp9Hrx9UjyARxcbvTy_m412YAwZ4sMDjZCmDP9NyI8kWHLKoNFFxJExIM-fBTWxELDq6RinTm_qRprAeO7QXmkpvjsjuUjezSMRJBX8b-u20InNxsEY4S3CHFnRpsz0gfH-rdw_TVJt4FCt-e2wA",
  "payload": "e30"
}
2025-07-14 00:17:23,820:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2527025161/552413074841/lrf9oQ HTTP/1.1" 200 195
2025-07-14 00:17:23,821:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 14 Jul 2025 00:17:23 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2527025161
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2527025161/552413074841>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/lrf9oQ
Replay-Nonce: 6etVd_hwKpKQPHyNmpUokyE9EA6_5CsT1PGMpK8JD3ZAZ0EAkIM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/lrf9oQ",
  "status": "pending",
  "token": "4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI"
}
2025-07-14 00:17:23,821:DEBUG:acme.client:Storing nonce: 6etVd_hwKpKQPHyNmpUokyE9EA6_5CsT1PGMpK8JD3ZAZ0EAkIM
2025-07-14 00:17:23,822:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-07-14 00:17:24,823:DEBUG:acme.client:JWS payload:
b''
2025-07-14 00:17:24,825:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2527025161/552413074841:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjUyNzAyNTE2MSIsICJub25jZSI6ICI2ZXRWZF9od0twS1FQSHlObXBVb2t5RTlFQTZfNUNzVDFQR01wSzhKRDNaQVowRUFrSU0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzI1MjcwMjUxNjEvNTUyNDEzMDc0ODQxIn0",
  "signature": "hEPPQxk05Lvj6VnV6O7OD2CdjmFpq8POVx_z8nyVlPqtPFO5oiJo0wi60mAR_SWlzdV-__EXA6ZTWwklkAQZe-ep7E__y_qD4MGHx65AGKARsDdPHJoCWGfy3pyqS1crOGOkiJ5qj667r8-32FlG3RRpYoNaFGaGn1ChLVYgSPjRegBYYbTtr506DC9GnxlhbyQZS9E-bCDXXiVxXcGSBazqFdGwYwX9jtQbLjLBm3KgL1PFRX8u6ReQwgIfDzNJPcHftJz4sIlypGEbe0WRtrkE6WZKWmsL_6Eak0MKR5_Xt9_mrn7z1avbl61ngHn6JeCvRnSfvuOTYqD1jSkksg",
  "payload": ""
}
2025-07-14 00:17:25,023:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2527025161/552413074841 HTTP/1.1" 200 1066
2025-07-14 00:17:25,025:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 14 Jul 2025 00:17:24 GMT
Content-Type: application/json
Content-Length: 1066
Connection: keep-alive
Boulder-Requester: 2527025161
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 6etVd_hwkUWWq_3WqWsvoBg3HoHNpekguIUcdCgHjCQi-aqaqSs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "api.rcdigitais.com.br"
  },
  "status": "invalid",
  "expires": "2025-07-21T00:17:23Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2527025161/552413074841/lrf9oQ",
      "status": "invalid",
      "validated": "2025-07-14T00:17:23Z",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "186.248.251.231: Fetching http://api.rcdigitais.com.br/.well-known/acme-challenge/4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI: Connection refused",
        "status": 400
      },
      "token": "4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI",
      "validationRecord": [
        {
          "url": "http://api.rcdigitais.com.br/.well-known/acme-challenge/4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI",
          "hostname": "api.rcdigitais.com.br",
          "port": "80",
          "addressesResolved": [
            "186.248.251.231"
          ],
          "addressUsed": "186.248.251.231"
        }
      ]
    }
  ]
}
2025-07-14 00:17:25,025:DEBUG:acme.client:Storing nonce: 6etVd_hwkUWWq_3WqWsvoBg3HoHNpekguIUcdCgHjCQi-aqaqSs
2025-07-14 00:17:25,026:INFO:certbot._internal.auth_handler:Challenge failed for domain api.rcdigitais.com.br
2025-07-14 00:17:25,026:INFO:certbot._internal.auth_handler:http-01 challenge for api.rcdigitais.com.br
2025-07-14 00:17:25,026:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: api.rcdigitais.com.br
  Type:   connection
  Detail: 186.248.251.231: Fetching http://api.rcdigitais.com.br/.well-known/acme-challenge/4MLnjTc1AcMI5pSQGmd5-7XMzq-NIlVd62a_giXZtTI: Connection refused

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

2025-07-14 00:17:25,028:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/src/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/src/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-07-14 00:17:25,029:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-07-14 00:17:25,029:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-07-14 00:17:25,030:DEBUG:certbot._internal.plugins.standalone:Stopping server at :::80...
2025-07-14 00:17:25,144:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/main.py", line 1879, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/main.py", line 1585, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/client.py", line 524, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/client.py", line 425, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/client.py", line 503, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/src/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/src/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-07-14 00:17:25,152:ERROR:certbot._internal.log:Some challenges have failed.
